TOP_DIR = ../..
sinclude $(TOP_DIR)/tools/W800/conf.mk

ifndef PDIR
GEN_LIBS = libwmcomponent$(LIB_EXT)
COMPONENTS_libwmcomponent = ascii_fonts/libasciifonts$(LIB_EXT)
endif

#DEFINES +=

sinclude $(TOP_DIR)/tools/W800/rules.mk

PDIR := ../$(PDIR)
sinclude $(PDIR)Makefile
